spring.application.name=moviebooking-server
spring.datasource.url=jdbc:sqlserver://localhost;trustServerCertificate=true;databaseName=MovieBooking
#spring.datasource.url=jdbc:sqlserver://26.2.102.103;instanceName=SERVER;databaseName=MovieBooking;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=kc

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.port=8081

# JWT Configurations
jwt.secret=ZG9uZ3V5ZW5waHVvbmdqYXZhc2VjdXJpdHlkb25ndXllbnBodW9uZ2phdmFzZWN1cml0eWRvbmd1eWVucGh1b25namF2YXNlY3VyaXR5
jwt.expiration=86400000

# Swagger Configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# VNPay Configurations
vnpay.tmnCode=YNXTFN06
vnpay.hashSecret=EWF0W6GQNPU0WEVVPKO10D9G6Z991PFD
vnpay.paymentUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.returnUrl=http://localhost:5173/payment-return
vnpay.returnUrl=http://10.0.2.2:8081/api/vnpay-payment/vnpay_return
vnpay.version=2.1.0
vnpay.command=pay
vnpay.orderType=250000

# Email Configurations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phuongdonguyen03@gmail.com
spring.mail.password=zgkb xavg ujik ohkt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true