spring.application.name=moviebooking-server
spring.datasource.url=jdbc:sqlserver://localhost;trustServerCertificate=true;databaseName=MovieBooking
spring.datasource.username=sa
spring.datasource.password=kc

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.port=8081

# JWT Configurations
jwt.secret=ZG9uZ3V5ZW5waHVvbmdqYXZhc2VjdXJpdHlkb25ndXllbnBodW9uZ2phdmFzZWN1cml0eWRvbmd1eWVucGh1b25namF2YXNlY3VyaXR5
jwt.expiration=86400000

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# Enable Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
# OpenAPI JSON path
springdoc.api-docs.path=/v3/api-docs

# Sort APIs by method or alphabetically
springdoc.swagger-ui.operationsSorter=method

# Application title and description
springdoc.info.title=Movie Booking Server API
springdoc.info.description=API documentation for the Movie Booking Server application
springdoc.info.version=v1.0.0